### ISSUE TITLE
not weexpack project

### ISSUE THREAD

**Issue by yuanlove521** [weexteam/weex-hackernews#64]
执行weexpack plugin add nat-communication命令时报错；
Error: Current working directory is not a weexpack project

**Comment by Acathur** [comment]
Use `weex create` to init your weex project.

**Comment by nagerenshifou** [comment]
实在太坑了，weex init和weex create竟然不一样

**Comment by Hanks10100** [comment]
Yes, this project is not a weex-pack project. Because when developing this project the `weex-pack` doesn't support the Vue syntax yet, even the Weex SDK doesn't support Vue.js yet.

This project is built by the source of Weex SDK and Vue.js, and not rely on any version of Weex SDK. *I will replace those source to a published Weex SDK someday, maybe...*

For tool-related questions, you can file an issue at [`weex-pack`](https://github.com/weexteam/weex-pack) and [`weex-toolkit`](https://github.com/weexteam/weex-toolkit).
