### ISSUE TITLE
is this the current state of this app?

### ISSUE THREAD

**Issue by venkatesh3007** [weexteam/weex-hackernews#8]
@Hanks10100 - Can you confirm if the screenshot below is what I should expect with the recent code?
 
![screenshot_20161229-205555](https://cloud.githubusercontent.com/assets/3645443/21547137/1c60374a-ce0a-11e6-8fa7-60f13f83937c.png)

I think you are working on the implementation of  native vue-router. I would like to help you out in getting this thing done faster.

**Comment by Jinjiang** [comment]
Yes and I found some problem:

1. Can not see the top `<header>` https://github.com/weexteam/weex-hackernews/blob/master/src/components/header.vue
2. Can not see expand/collapse button in `<comment>` https://github.com/weexteam/weex-hackernews/blob/master/src/components/comment.vue#L3:L4
3. Doesn't support back button of OS (because its abstract vue-router mode so it isn't a bug, and of course the experience is a little strange)
4. I can see "Hello World" in the beginning of the App. Maybe it should be hidden. https://github.com/weexteam/weex-hackernews/blob/master/android/app/src/main/res/layout/activity_main.xml#L13:L16

**Comment by Hanks10100** [comment]
Yeah, the screenshot is correct on Android currently, but not the result I want ...

I have just fixed some problems on the iOS, the vue-router can work properly on iPhone now (without `<router-link>`) .

I am a front-end developer, not good at Android. I would be very glad if you can help me solve these problems. Feel free to add your code.

**Comment by venkatesh3007** [comment]
@Hanks10100 - Sure.

**Comment by Jinjiang** [comment]
@venkatesh3007 @Hanks10100 I've fixed almost of them above. Today I could fixed the last two problems :-)

**Comment by venkatesh3007** [comment]
@Jinjiang - Great. I will take a pull from your fork and see if it's working for me.

**Comment by venkatesh3007** [comment]
@Jinjiang - It works. But hacker news logo isn't visible in android. Same as #10 in iOS.

**Comment by Jinjiang** [comment]
I fixed it in iOS by this commit:
https://github.com/weexteam/weex-hackernews/commit/8037287c6e96db549fc6b0ecb76e3e4e8c778fec
Doest it work for you?

And Android is wip now :-)

**Comment by venkatesh3007** [comment]
> Doest it work for you?

I can't test it on iOS.

> And Android is wip now :-)

:+1:

**Comment by venkatesh3007** [comment]
@Jinjiang @Hanks10100  - Do you have a slack channel where we can discuss the developments for this app? It would be much faster.

**Comment by Jinjiang** [comment]
fixed https://github.com/weexteam/weex-hackernews/commit/5b1d9150b74cd80e4bcc1a4cec364eb1ff8cfff7

**Comment by Jinjiang** [comment]
Well finally onBackPressed event in Android works! All problems clear 😄

**Comment by Jinjiang** [comment]
We use slack quite few. Let me make a discussion in team later. Don't mind that 🙂

**Comment by venkatesh3007** [comment]
@Jinjiang - No problem about that and Happy New Year!
